#pragma once

#define ERR_IO_READ_DUP 0x02
#define ERR_IO_WRITE_DUP 0x03
#define ERR_TIMER_TABLE_FULL 0x04
#define ERR_TASK_TABLE_FULL 0x05
#define ERR_INT_ENTER_BAD_LEVEL 0x06
#define ERR_INT_EXIT_BAD_LEVEL 0x07
#define ERR_INT_RAISE_BAD_LEVEL 0x08
#define ERR_INT_RELEASE_BAD_LEVEL 0x09
